## Post request to create user
POST http://localhost:4000/user
Content-Type: application/json

{
  "firstname": "Cryser",
  "lastname": "Kelvin",
  "email": "christopher@gmail.com",
  "phonenumber": "+255755814817",
  "password": "123456"
} 